using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using Revert.Core.Extensions;

namespace Revert.Core.IO.Files
{
    public class MimeTypeExtractor
    {
        public static readonly HashSet<string> ImageFileTypes = new[]
        {
                "AAI", "ART", "ARW", "AVI", "AVS", "BMP", "BMP2", "BMP3", "CALS", "CGM", "CIN", "CMYK", "CMYKA", "CR2",
                "CRW", "CUR", "CUT", "DCM", "DCR", "DCX", "DIB", "DJVU", "DNG", "DOT", "DPX", "EMF", "EPI",
                "EPS", "EPS2", "EPS3", "EPSF", "EPSI", "EPT", "EXR", "FAX", "FIG", "FITS", "FPX", "GIF", "GPLT",
                "GRAY", "HDR", "HPGL", "HRZ", "ICO", "JBIG", "JNG", "JP2", "JPC", "JPEG",
                "JXR", "MAN", "MAT", "MIFF", "MONO", "MNG", "M2V", "MPEG", "MPC", "MPR", "MRW", "MSL", "MTV", "MVG",
                "NEF", "ORF", "OTB", "P7", "PALM", "PAM", "CLIPBOARD", "PBM", "PCD", "PCDS", "PCL", "PCX",
                "PEF", "PFA", "PFB", "PFM", "PGM", "PICON", "PICT", "PIX", "PNG", "PNG8", "PNG00", "PNG24",
                "PNG32", "PNG48", "PNG64", "PNM", "PPM", "PS", "PS2", "PS3", "PSB", "PSD", "PTIF", "PWP", "RAD",
                "RAF", "RGB", "RGBA", "RLA", "RLE", "SCT", "SFW", "SGI", "SHTML", "SID", "MRSID", "SPARSE-COLOR",
                "SUN", "SVG", "TGA", "TIFF", "TIM", "TTF", "UIL", "UYVY", "VICAR", "VIFF", "WBMP", "WDP",
                "WEBP", "WMF", "WPG", "X", "XBM", "XCF", "XPM", "XWD", "X3F", "YCBCR", "YCBCRA", "YUV"
            }.ToHashSet();

        public static HashSet<string> ExtractableFileTypes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "doc", "docx", "ppt", "pptx", "xls", "xlsx", "pdf", "txt", "rtf", "xml", ""
        };


        public static string GetMimeTypeFromFile(string filePath)
        {
            if (!File.Exists(filePath)) throw new FileNotFoundException(filePath + " not found");

            var buffer = new byte[256];
            using (var fs = new FileStream(filePath, FileMode.Open))
            {
                if (fs.Length >= 256) fs.Read(buffer, 0, 256);
                else fs.Read(buffer, 0, (int)fs.Length);
            }
            try
            {
                uint mimetype;
                FindMimeFromData(0, null, buffer, 256, null, 0, out mimetype, 0);
                var mimeTypePtr = new IntPtr(mimetype);
                var mime = Marshal.PtrToStringUni(mimeTypePtr);
                Marshal.FreeCoTaskMem(mimeTypePtr);
                return mime;
            }
            catch
            {
                return "unknown/unknown";
            }
        }

        // ReSharper disable InconsistentNaming
        [DllImport(@"urlmon.dll", CharSet = CharSet.Auto)]
        private extern static uint FindMimeFromData(

            uint pBC,
            [MarshalAs(UnmanagedType.LPStr)] string pwzUrl,
            [MarshalAs(UnmanagedType.LPArray)] byte[] pBuffer,
            uint cbSize,
            [MarshalAs(UnmanagedType.LPStr)] string pwzMimeProposed,
            uint dwMimeFlags,
            out uint ppwzMimeOut,
            uint dwReserverd
        );
        // ReSharper restore InconsistentNaming

        private static Dictionary<string, string> fileExtensionByMimeType = new Dictionary<string, string>()
        {
            {"unknown/unknown", "txt"},
            {"application/postscript", "ai"},
            {"audio/x-aiff", "aif"},
            {"text/plain", "asc"},
            {"application/atom+xml", "atom"},
            {"audio/basic", "au"},
            {"video/x-msvideo", "avi"},
            {"application/x-bcpio", "bcpio"},
            {"application/octet-stream", "bin"},
            {"image/bmp", "bmp"},
            {"application/x-netcdf", "cdf"},
            {"image/cgm", "cgm"},
            {"application/x-cpio", "cpio"},
            {"application/mac-compactpro", "cpt"},
            {"application/x-csh", "csh"},
            {"text/css", "css"},
            {"application/x-director", "dcr"},
            {"video/x-dv", "dif"},
            {"image/vnd.djvu", "djv"},
            {"application/msword", "doc"},
            {"application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx"},
            {"application/vnd.ms-word.document.macroEnabled.12", "docm"},
            {"application/vnd.openxmlformats-officedocument.wordprocessingml.template", "dotx"},
            {"application/vnd.ms-word.template.macroEnabled.12", "dotm"},
            {"application/xml-dtd", "dtd"},
            {"application/x-dvi", "dvi"},
            {"text/x-setext", "etx"},
            {"application/earthviewer", "kml"},
            {"application/andrew-inset", "ez"},
            {"image/gif", "gif"},
            {"application/srgs", "gram"},
            {"application/srgs+xml", "grxml"},
            {"application/x-gtar", "gtar"},
            {"application/x-hdf", "hdf"},
            {"application/mac-binhex40", "hqx"},
            {"text/html", "htm"},
            {"x-conference/x-cooltalk", "ice"},
            {"image/x-icon", "ico"},
            {"text/calendar", "ics"},
            {"image/ief", "ief"},
            {"model/iges", "iges"},
            {"application/x-java-jnlp-file", "jnlp"},
            {"image/jp2", "jp2"},
            {"image/jpeg", "jpe"},
            {"application/x-javascript", "js"},
            {"audio/midi", "kar"},
            {"application/x-latex", "latex"},
            {"audio/x-mpegurl", "m3u"},
            {"audio/mp4a-latm", "m4a"},
            {"video/vnd.mpegurl", "m4u"},
            {"video/x-m4v", "m4v"},
            {"image/x-macpaint", "mac"},
            {"application/x-troff-man", "man"},
            {"application/mathml+xml", "mathml"},
            {"application/x-troff-me", "me"},
            {"model/mesh", "mesh"},
            {"application/vnd.mif", "mif"},
            {"video/quicktime", "mov"},
            {"video/x-sgi-movie", "movie"},
            {"audio/mpeg", "mp2"},
            {"video/mp4", "mp4"},
            {"video/mpeg", "mpe"},
            {"application/x-troff-ms", "ms"},
            {"application/oda", "oda"},
            {"application/ogg", "ogg"},
            {"application/msonenote", "one"},
            {"image/x-portable-bitmap", "pbm"},
            {"image/pict", "pct"},
            {"chemical/x-pdb", "pdb"},
            {"application/pdf", "pdf"},
            {"image/x-portable-graymap", "pgm"},
            {"application/x-chess-pgn", "pgn"},
            {"image/png", "png"},
            {"image/x-portable-anymap", "pnm"},
            {"application/vnd.ms-powerpoint.template.macroEnabled.12", "potm"},
            {"application/vnd.openxmlformats-officedocument.presentationml.template", "potx"},
            {"application/vnd.ms-powerpoint.addin.macroEnabled.12", "ppam"},
            {"image/x-portable-pixmap", "ppm"},
            {"application/vnd.ms-powerpoint", "ppt"},
            {"application/vnd.openxmlformats-officedocument.presentationml.presentation", "pptx"},
            {"application/vnd.ms-powerpoint.presentation.macroEnabled.12", "pptm"},
            {"application/vnd.openxmlformats-officedocument.presentationml.slideshow", "ppsx"},
            {"application/vnd.ms-powerpoint.slideshow.macroEnabled.12", "ppsm"},
            {"image/x-quicktime", "qti"},
            {"audio/x-pn-realaudio", "ra"},
            {"image/x-cmu-raster", "ras"},
            {"application/rdf+xml", "rdf"},
            {"image/x-rgb", "rgb"},
            {"application/vnd.rn-realmedia", "rm"},
            {"application/x-troff", "roff"},
            {"text/rtf", "rtf"},
            {"text/richtext", "rtx"},
            {"text/sgml", "sgm"},
            {"application/x-sh", "sh"},
            {"application/x-shar", "shar"},
            {"application/x-stuffit", "sit"},
            {"application/x-koan", "skd"},
            {"application/vnd.ms-powerpoint.slide.macroEnabled.12", "sldm"},
            {"application/vnd.openxmlformats-officedocument.presentationml.slide", "sldx"},
            {"application/smil", "smi"},
            {"application/x-futuresplash", "spl"},
            {"application/x-wais-source", "src"},
            {"application/x-sv4cpio", "sv4cpio"},
            {"application/x-sv4crc", "sv4crc"},
            {"image/svg+xml", "svg"},
            {"application/x-shockwave-flash", "swf"},
            {"application/x-tar", "tar"},
            {"application/x-tcl", "tcl"},
            {"application/x-tex", "tex"},
            {"application/x-texinfo", "texi"},
            {"application/vnd.ms-officetheme", "thmx"},
            {"image/tiff", "tif"},
            {"text/tab-separated-values", "tsv"},
            {"application/x-ustar", "ustar"},
            {"application/x-cdlink", "vcd"},
            {"model/vrml", "vrml"},
            {"application/voicexml+xml", "vxml"},
            {"audio/x-wav", "wav"},
            {"image/vnd.wap.wbmp", "wbmp"},
            {"application/vnd.wap.wbxml", "wbmxl"},
            {"text/vnd.wap.wml", "wml"},
            {"application/vnd.wap.wmlc", "wmlc"},
            {"text/vnd.wap.wmlscript", "wmls"},
            {"application/vnd.wap.wmlscriptc", "wmlsc"},
            {"image/x-xbitmap", "xbm"},
            {"application/xhtml+xml", "xht"},
            {"application/vnd.ms-excel.addin.macroEnabled.12", "xlam"},
            {"application/vnd.ms-excel", "xls"},
            {"application/vnd.ms-excel.sheet.binary.macroEnabled.12", "xlsb"},
            {"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"},
            {"application/vnd.ms-excel.sheet.macroEnabled.12", "xlsm"},
            {"application/vnd.openxmlformats-officedocument.spreadsheetml.template", "xltx"},
            {"application/vnd.ms-excel.template.macroEnabled.12", "xltm"},
            {"application/xml", "xml"},
            {"image/x-xpixmap", "xpm"},
            {"application/xslt+xml", "xslt"},
            {"application/vnd.mozilla.xul+xml", "xul"},
            {"image/x-xwindowdump", "xwd"},
            {"chemical/x-xyz", "xyz"},
            {"application/zip", "zip"},
            {"application/x-zip-compressed", "zip"}
        };

        public string ConvertMimeTypeByFileExtensionToFileExtensionByMimeType()
        {
            var fileExtensionsByMimeTypeInnerText = new StringBuilder();
            var mimeTypes = new HashSet<string>();

            foreach (var item in mimeTypeByFileExtension)
            {
                if (!mimeTypes.Add(item.Value)) continue;
                if (fileExtensionsByMimeTypeInnerText.Length != 0) fileExtensionsByMimeTypeInnerText.AppendLine(",");
                fileExtensionsByMimeTypeInnerText.Append(string.Format("{{\"{0}\", \"{1}\"}}", item.Value, item.Key));
            }

            return string.Format("private static Dictionary<string, string> fileExtensionByMimeType = new Dictionary<string, string>(){0}{{{0}{1}}};",
                Environment.NewLine, fileExtensionsByMimeTypeInnerText);
        }


        private static Dictionary<string, string> mimeTypeByFileExtension = new Dictionary<string, string>()
        {
            {"ai", "application/postscript"},
            {"aif", "audio/x-aiff"},
            {"aifc", "audio/x-aiff"},
            {"aiff", "audio/x-aiff"},
            {"asc", "text/plain"},
            {"atom", "application/atom+xml"},
            {"au", "audio/basic"},
            {"avi", "video/x-msvideo"},
            {"bcpio", "application/x-bcpio"},
            {"bin", "application/octet-stream"},
            {"bmp", "image/bmp"},
            {"cdf", "application/x-netcdf"},
            {"cgm", "image/cgm"},
            {"class", "application/octet-stream"},
            {"cpio", "application/x-cpio"},
            {"cpt", "application/mac-compactpro"},
            {"csh", "application/x-csh"},
            {"css", "text/css"},
            {"dcr", "application/x-director"},
            {"dif", "video/x-dv"},
            {"dir", "application/x-director"},
            {"djv", "image/vnd.djvu"},
            {"djvu", "image/vnd.djvu"},
            {"dll", "application/octet-stream"},
            {"dmg", "application/octet-stream"},
            {"dms", "application/octet-stream"},
            {"doc", "application/msword"},
            {"docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
            {"docm", "application/vnd.ms-word.document.macroEnabled.12"},
            {"dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template"},
            {"dotm", "application/vnd.ms-word.template.macroEnabled.12"},
            {"dtd", "application/xml-dtd"},
            {"dv", "video/x-dv"},
            {"dvi", "application/x-dvi"},
            {"dxr", "application/x-director"},
            {"eps", "application/postscript"},
            {"etx", "text/x-setext"},
            {"exe", "application/octet-stream"},
            {"ez", "application/andrew-inset"},
            {"gif", "image/gif"},
            {"gram", "application/srgs"},
            {"grxml", "application/srgs+xml"},
            {"gtar", "application/x-gtar"},
            {"hdf", "application/x-hdf"},
            {"hqx", "application/mac-binhex40"},
            {"htm", "text/html"},
            {"html", "text/html"},
            {"ice", "x-conference/x-cooltalk"},
            {"ico", "image/x-icon"},
            {"ics", "text/calendar"},
            {"ief", "image/ief"},
            {"ifb", "text/calendar"},
            {"iges", "model/iges"},
            {"igs", "model/iges"},
            {"jnlp", "application/x-java-jnlp-file"},
            {"jp2", "image/jp2"},
            {"jpe", "image/jpeg"},
            {"jpeg", "image/jpeg"},
            {"jpg", "image/jpeg"},
            {"js", "application/x-javascript"},
            {"kar", "audio/midi"},
            {"latex", "application/x-latex"},
            {"lha", "application/octet-stream"},
            {"lzh", "application/octet-stream"},
            {"m3u", "audio/x-mpegurl"},
            {"m4a", "audio/mp4a-latm"},
            {"m4b", "audio/mp4a-latm"},
            {"m4p", "audio/mp4a-latm"},
            {"m4u", "video/vnd.mpegurl"},
            {"m4v", "video/x-m4v"},
            {"mac", "image/x-macpaint"},
            {"man", "application/x-troff-man"},
            {"mathml", "application/mathml+xml"},
            {"me", "application/x-troff-me"},
            {"mesh", "model/mesh"},
            {"mid", "audio/midi"},
            {"midi", "audio/midi"},
            {"mif", "application/vnd.mif"},
            {"mov", "video/quicktime"},
            {"movie", "video/x-sgi-movie"},
            {"mp2", "audio/mpeg"},
            {"mp3", "audio/mpeg"},
            {"mp4", "video/mp4"},
            {"mpe", "video/mpeg"},
            {"mpeg", "video/mpeg"},
            {"mpg", "video/mpeg"},
            {"mpga", "audio/mpeg"},
            {"ms", "application/x-troff-ms"},
            {"msh", "model/mesh"},
            {"mxu", "video/vnd.mpegurl"},
            {"nc", "application/x-netcdf"},
            {"oda", "application/oda"},
            {"ogg", "application/ogg"},
            {"one", "application/msonenote"},
            {"onetoc2", "application/msonenote"},
            {"onetmp", "application/msonenote"},
            {"onepkg", "application/msonenote"},
            {"pbm", "image/x-portable-bitmap"},
            {"pct", "image/pict"},
            {"pdb", "chemical/x-pdb"},
            {"pdf", "application/pdf"},
            {"pgm", "image/x-portable-graymap"},
            {"pgn", "application/x-chess-pgn"},
            {"pic", "image/pict"},
            {"pict", "image/pict"},
            {"png", "image/png"},
            {"pnm", "image/x-portable-anymap"},
            {"pnt", "image/x-macpaint"},
            {"pntg", "image/x-macpaint"},
            {"potm", "application/vnd.ms-powerpoint.template.macroEnabled.12"},
            {"potx", "application/vnd.openxmlformats-officedocument.presentationml.template"},
            {"ppam", "application/vnd.ms-powerpoint.addin.macroEnabled.12"},
            {"ppm", "image/x-portable-pixmap"},
            {"ppt", "application/vnd.ms-powerpoint"},
            {"pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
            {"pptm", "application/vnd.ms-powerpoint.presentation.macroEnabled.12"},
            {"ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow"},
            {"ppsm", "application/vnd.ms-powerpoint.slideshow.macroEnabled.12"},
            {"ps", "application/postscript"},
            {"qt", "video/quicktime"},
            {"qti", "image/x-quicktime"},
            {"qtif", "image/x-quicktime"},
            {"ra", "audio/x-pn-realaudio"},
            {"ram", "audio/x-pn-realaudio"},
            {"ras", "image/x-cmu-raster"},
            {"rdf", "application/rdf+xml"},
            {"rgb", "image/x-rgb"},
            {"rm", "application/vnd.rn-realmedia"},
            {"roff", "application/x-troff"},
            {"rtf", "text/rtf"},
            {"rtx", "text/richtext"},
            {"sgm", "text/sgml"},
            {"sgml", "text/sgml"},
            {"sh", "application/x-sh"},
            {"shar", "application/x-shar"},
            {"silo", "model/mesh"},
            {"sit", "application/x-stuffit"},
            {"skd", "application/x-koan"},
            {"skm", "application/x-koan"},
            {"skp", "application/x-koan"},
            {"skt", "application/x-koan"},
            {"sldm", "application/vnd.ms-powerpoint.slide.macroEnabled.12"},
            {"sldx", "application/vnd.openxmlformats-officedocument.presentationml.slide"},
            {"smi", "application/smil"},
            {"smil", "application/smil"},
            {"snd", "audio/basic"},
            {"so", "application/octet-stream"},
            {"spl", "application/x-futuresplash"},
            {"src", "application/x-wais-source"},
            {"sv4cpio", "application/x-sv4cpio"},
            {"sv4crc", "application/x-sv4crc"},
            {"svg", "image/svg+xml"},
            {"swf", "application/x-shockwave-flash"},
            {"t", "application/x-troff"},
            {"tar", "application/x-tar"},
            {"tcl", "application/x-tcl"},
            {"tex", "application/x-tex"},
            {"texi", "application/x-texinfo"},
            {"texinfo", "application/x-texinfo"},
            {"thmx", "application/vnd.ms-officetheme"},
            {"tif", "image/tiff"},
            {"tiff", "image/tiff"},
            {"tr", "application/x-troff"},
            {"tsv", "text/tab-separated-values"},
            {"txt", "text/plain"},
            {"ustar", "application/x-ustar"},
            {"vcd", "application/x-cdlink"},
            {"vrml", "model/vrml"},
            {"vxml", "application/voicexml+xml"},
            {"wav", "audio/x-wav"},
            {"wbmp", "image/vnd.wap.wbmp"},
            {"wbmxl", "application/vnd.wap.wbxml"},
            {"wml", "text/vnd.wap.wml"},
            {"wmlc", "application/vnd.wap.wmlc"},
            {"wmls", "text/vnd.wap.wmlscript"},
            {"wmlsc", "application/vnd.wap.wmlscriptc"},
            {"wrl", "model/vrml"},
            {"xbm", "image/x-xbitmap"},
            {"xht", "application/xhtml+xml"},
            {"xhtml", "application/xhtml+xml"},
            {"xlam", "application/vnd.ms-excel.addin.macroEnabled.12"},
            {"xls", "application/vnd.ms-excel"},
            {"xlsb", "application/vnd.ms-excel.sheet.binary.macroEnabled.12"},
            {"xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
            {"xlsm", "application/vnd.ms-excel.sheet.macroEnabled.12"},
            {"xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template"},
            {"xltm", "application/vnd.ms-excel.template.macroEnabled.12"},
            {"xml", "application/xml"},
            {"xpm", "image/x-xpixmap"},
            {"xsl", "application/xml"},
            {"xslt", "application/xslt+xml"},
            {"xul", "application/vnd.mozilla.xul+xml"},
            {"xwd", "image/x-xwindowdump"},
            {"xyz", "chemical/x-xyz"},
            {"zip", "application/zip"}
        };
    }
}
